### PR TITLE
add type hints

### PR DESCRIPTION
**Pull request by plming**
I've added type hints for parameters and returns.
I referenced mostly docstring, implementation at few points.
It doesn't affect any runtime behavior and I checked all test passed!

### CODE REVIEW

**Comment by mthh** [comment]
Thank you! This is something I had thought of but didn't jump into!

Your type hints seem intuitively correct but when testing with mypy I have some errors. I think it's due to inconsistencies between some of my code and the documentation in the docstrings (which must have guided your additions).
I will just play a bit with the type hints and mypy to see if I merge it as it or if I take the opportunity to modify the docstrings and some of your hint types.

**Comment by mthh** [comment]
Is this OK if I push further modifications to your `type-hint` branch so that we can track it on the same PR ?

**Comment by plming** [comment]
Sure! Thanks for working :)

**Comment by plming** [comment]
All good! But before we go, I fixed docstring with exact type hints. Please check it, and then fine to merge it!

**Comment by mthh** [comment]
Indeed, thanks!

And thank you for this useful contribution!

I will release a new version later today.

**Pull request merged**
